### ISSUE TITLE
tags link to wrong page

### ISSUE THREAD

**Issue by k24883** [robbyedwards/octopress-tag-pages#2]
All generated tags are just linking to $tag and not to http://$domain/tags/$tag
where can I change this?
thx

**Comment by akda5id** [comment]
Quick fix is to add 'tag_dir: tags' or whatever you want it to be to your _config.yml

Proper fix would make the default (tags) carry to the linking code. I might submit that once I work my head around jekyll plugins.

**Comment by robbyedwards** [comment]
I added the default directory `tags` to the link creation. This should fix this issue; seems to work for me. It was an oversight on my part, since I use the `tag_dir` bit in my `_config.yml` which worked just fime, I didn't notice it. Thanks for the heads up, and I'm sorry this took so long for me to get around to fixing.
